pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                // dir('bugtracker-backend') {
                //     sh 'go test -v ./...'
                // }
                script {
                    // create a writable cache directory
                    sh 'mkdir -p $WORKSPACE/.gocache'
                    sh 'export GOCACHE=$WORKSPACE/.gocache'

                    dir('bugtracker-backend') {
                        sh '''
                            export GOCACHE=$WORKSPACE/.gocache
                            go test -v ./...
                        '''
                    }
                }
            }
        }
    }
} 