pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                // dir('bugtracker-backend') {
                //     sh 'go test -v ./...'
                // }
                script {
                    sh '''
                        mkdir -p $WORKSPACE/.gocache
                        mkdir -p $WORKSPACE/.gomod
                        mkdir -p $WORKSPACE/.gopath

                        export GOCACHE=$WORKSPACE/.gocache
                        export GOMODCACHE=$WORKSPACE/.gomod
                        export GOPATH=$WORKSPACE/.gopath
                    '''

                    dir('bugtracker-backend') {
                        sh '''
                            export GOCACHE=$WORKSPACE/.gocache
                            export GOMODCACHE=$WORKSPACE/.gomod
                            export GOPATH=$WORKSPACE/.gopath
                            go test -v ./... 2>&1 | go-junit-report > test-results.xml
                        '''
                    }
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }
        stage('Unit Test - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        
        
        }
    }
} 